#!/usr/bin/env python3
"""
protect_generated_files.py — Claude Code PreToolUse hook.
Blocks Edit/Write/MultiEdit calls that target files DevBureau auto-generates
via sync_ide.py, redirecting the agent to the real source file instead.
Registered in .claude/settings.json by sync_ide.py's generate_claude_config().
"""
import json
import sys
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stderr.reconfigure(encoding="utf-8")
    except AttributeError:
        pass

# Exact paths (relative to repo root) that sync_ide.py overwrites on every run.
PROTECTED_FILES: dict[str, str] = {
    ".claude/CLAUDE.md": ".agent/rules/DEVBUREAU.md",
    "AGENTS.md": ".agent/rules/DEVBUREAU.md",
    "GEMINI.md": ".agent/rules/DEVBUREAU.md",
    ".github/copilot-instructions.md": ".agent/rules/DEVBUREAU.md",
    ".windsurfrules": ".agent/rules/DEVBUREAU.md",
    ".clinerules": ".agent/rules/DEVBUREAU.md",
    ".roorules": ".agent/rules/DEVBUREAU.md",
    ".rules": ".agent/rules/DEVBUREAU.md",
}

# Directory prefixes that are entirely auto-generated.
PROTECTED_PREFIXES: dict[str, str] = {
    ".cursor/rules/": ".agent/rules/DEVBUREAU.md or the relevant .agent/agents/*.md file",
    ".github/instructions/": ".agent/rules/DEVBUREAU.md or the relevant .agent/agents/*.md file",
}


def find_real_source(relative_path: str) -> str | None:
    if relative_path in PROTECTED_FILES:
        return PROTECTED_FILES[relative_path]
    for prefix, source_hint in PROTECTED_PREFIXES.items():
        if relative_path.startswith(prefix):
            return source_hint
    return None


def main() -> None:
    try:
        payload = json.loads(sys.stdin.read())
    except json.JSONDecodeError:
        sys.exit(0)

    file_path = payload.get("tool_input", {}).get("file_path", "")
    cwd = payload.get("cwd", "")
    if not file_path or not cwd:
        sys.exit(0)

    try:
        relative_path = Path(file_path).resolve().relative_to(Path(cwd).resolve()).as_posix()
    except ValueError:
        sys.exit(0)

    real_source = find_real_source(relative_path)
    if real_source is None:
        sys.exit(0)

    print(
        f"Blocked: '{relative_path}' is auto-generated by sync_ide.py - edits here "
        f"are overwritten on the next sync. Edit {real_source} instead, then run "
        f"`python .agent/scripts/sync_ide.py --target all`.",
        file=sys.stderr,
    )
    sys.exit(2)


if __name__ == "__main__":
    main()
